# Generated by Django 4.2.16 on 2024-11-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ad',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
