# Generated by Django 4.2.16 on 2024-12-04 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0041_packagesize_unit_type_product_discount_percentage_and_more'),
        ('Account', '0002_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of the coupon.')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicable_brands', models.TextField(blank=True, null=True)),
                ('applicable_products', models.TextField(blank=True, null=True)),
                ('additional_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='Products.brand')),
            ],
        ),
    ]
