# Generated by Django 4.2.16 on 2024-11-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_order_prescription_orderitem_order_products_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='Account_ord_user_id_68753b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='Account_ord_status_f80d23_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='Account_ord_order_d_35b5b8_idx'),
        ),
    ]
