# Generated by Django 4.2.16 on 2024-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_customer_address_type_userprofile_is_professional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_address_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
