# Generated by Django 4.2.16 on 2024-11-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Plans', '0002_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
