# Generated by Django 4.2.16 on 2024-11-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Plans', '0008_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contacts', to='Health_Plans.plan'),
        ),
    ]
