# Generated by Django 4.2.16 on 2024-11-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('safety_info', models.CharField(default='Safe', max_length=100)),
                ('num_tests', models.IntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='Health_Checkup.category_s')),
            ],
        ),
        migrations.CreateModel(
            name='Test_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthpackages',
            name='category',
        ),
        migrations.RemoveField(
            model_name='healthpackages',
            name='tests_included',
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
        migrations.DeleteModel(
            name='HealthPackages',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.AddField(
            model_name='health_packages',
            name='tests_included',
            field=models.ManyToManyField(related_name='packages', to='Health_Checkup.test_s'),
        ),
    ]
