# Generated by Django 4.2.16 on 2024-11-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0002_category_s_health_packages_test_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_packages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='health_packages',
            name='symptoms',
        ),
    ]
