# Generated by Django 4.2.16 on 2024-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0003_remove_health_packages_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_s',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
