# Generated by Django 4.2.16 on 2024-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0004_category_s_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_s',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
