# Generated by Django 4.2.16 on 2024-11-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0005_category_s_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_s',
            old_name='description',
            new_name='answer',
        ),
    ]
