# Generated by Django 4.2.16 on 2024-11-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0006_rename_description_category_s_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alternate_names', models.TextField(blank=True, null=True)),
                ('sample_requirements', models.TextField(blank=True, null=True)),
                ('allowed_genders', models.TextField(blank=True, null=True)),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='health_packages',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='Health_Checkup.category_s'),
        ),
    ]
