# Generated by Django 4.2.16 on 2024-11-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0008_alter_testdetail_allowed_genders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetail',
            name='allowed_genders',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('BOTH', 'Both')], default='BOTH', max_length=6),
        ),
    ]
