# Generated by Django 4.2.16 on 2024-11-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0009_alter_testdetail_allowed_genders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdetail',
            old_name='name',
            new_name='package',
        ),
    ]
