# Generated by Django 4.2.16 on 2024-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0010_rename_name_testdetail_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdetail',
            name='package',
        ),
    ]
