# Generated by Django 4.2.16 on 2024-11-15 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Checkup', '0011_remove_testdetail_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 11, 15, 18, 30, 25, 5578, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testdetail',
            name='allowed_genders',
            field=models.TextField(blank=True, null=True),
        ),
    ]
