# Generated by Django 4.2.16 on 2024-11-18 22:03

import Medicine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to=Medicine.models.file_upload_to_dr_profile)),
            ],
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=255)),
                ('country_of_origin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketer', to='Medicine.country')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('vial', 'Vial'), ('prefilled_syringe', 'Prefilled Syringe'), ('strip', 'Strip'), ('box', 'Box'), ('bottle', 'Bottle')], max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to=Medicine.models.file_upload_to_medicine_home)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prescription_required', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='Medicine.marketer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(default='MCQ', max_length=50)),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('option_e', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SaltComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecase', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.question')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeAndMedicineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('delivery_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit_type', models.CharField(choices=[('vial', 'Vial'), ('prefilled_syringe', 'Prefilled Syringe'), ('strip', 'Strip'), ('box', 'Box'), ('bottle', 'Bottle')], max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_medicine_details', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='PatientConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicine.category')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medicine.dr')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MissedDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_dose', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=Medicine.models.file_upload_to_medicine_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_image', to='Medicine.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='salt_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.saltcomposition'),
        ),
        migrations.CreateModel(
            name='HowToUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_to_use', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='HowDrugWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.CharField(max_length=100)),
                ('a_description', models.TextField()),
                ('pregnancy', models.CharField(max_length=100)),
                ('p_description', models.TextField()),
                ('breast_feeding', models.CharField(max_length=100)),
                ('b_description', models.TextField()),
                ('driving', models.CharField(max_length=100)),
                ('d_description', models.TextField()),
                ('kidney', models.CharField(max_length=100)),
                ('k_description', models.TextField()),
                ('liver', models.CharField(max_length=100)),
                ('l_description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_drug_works', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='FactBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemmical_class', models.CharField(max_length=100)),
                ('habit_forming', models.CharField(max_length=100)),
                ('therapeutic_class', models.CharField(max_length=100)),
                ('action_class', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factbox', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_reviewed', to='Medicine.dr')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_written', to='Medicine.dr')),
            ],
        ),
    ]
