# Generated by Django 4.2.16 on 2024-11-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='country_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer', to='Medicine.country'),
        ),
    ]
