# Generated by Django 4.2.16 on 2024-11-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_alter_marketer_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='views',
        ),
    ]
