# Generated by Django 4.2.16 on 2024-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0003_remove_medicine_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
