# Generated by Django 4.2.16 on 2024-11-19 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0004_alter_usecase_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowDrugWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_drug_works', to='Medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.CharField(max_length=100)),
                ('a_description', models.TextField()),
                ('pregnancy', models.CharField(max_length=100)),
                ('p_description', models.TextField()),
                ('breast_feeding', models.CharField(max_length=100)),
                ('b_description', models.TextField()),
                ('driving', models.CharField(max_length=100)),
                ('d_description', models.TextField()),
                ('kidney', models.CharField(max_length=100)),
                ('k_description', models.TextField()),
                ('liver', models.CharField(max_length=100)),
                ('l_description', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_advice', to='Medicine.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='medicine',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='sideeffect', to='Medicine.medicine'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HowDrugWorks',
        ),
    ]
