# Generated by Django 4.2.16 on 2024-11-19 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0005_howdrugwork_safetyadvice_sideeffect_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktip',
            name='medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quick_tips', to='Medicine.medicine'),
            preserve_default=False,
        ),
    ]
