# Generated by Django 4.2.16 on 2024-12-06 10:34

import Products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=Products.models.file_upload_to_brand)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=Products.models.file_upload_to_category)),
                ('views', models.IntegerField(default=0)),
                ('ad', models.ManyToManyField(blank=True, null=True, related_name='categories', to='Products.ad')),
                ('brand', models.ManyToManyField(related_name='category', to='Products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('jar', 'Jar'), ('tube', 'Tube'), ('strip', 'Strip'), ('combo_pack', 'Combo Pack'), ('pump_bottle', 'Pump Bottle'), ('packet', 'Packet'), ('sachet', 'Sachet'), ('box', 'Box'), ('bottle', 'Bottle')], max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_on_sale', models.CharField(choices=[('null', 'Null'), ('sell', 'Sell'), ('best_seller', 'Best Seller')], default='null')),
                ('sale_start_date', models.DateTimeField(blank=True, null=True)),
                ('sale_end_date', models.DateTimeField(blank=True, null=True)),
                ('unit_type', models.CharField(choices=[('jar', 'Jar'), ('tube', 'Tube'), ('strip', 'Strip'), ('combo_pack', 'Combo Pack'), ('pump_bottle', 'Pump Bottle'), ('packet', 'Packet'), ('sachet', 'Sachet'), ('box', 'Box'), ('bottle', 'Bottle')], max_length=50)),
                ('quantity', models.CharField(max_length=255)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Products.models.file_upload_to_products)),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('prescription_required', models.BooleanField(blank=True, default=False, null=True)),
                ('sku', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('delivery_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('num_ratings', models.IntegerField(default=0)),
                ('num_reviews', models.IntegerField(default=0)),
                ('recent_reviews', models.JSONField(default=list)),
                ('review_summary', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.brand')),
                ('category', models.ManyToManyField(related_name='products', to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=Products.models.file_upload_to_categorytype)),
                ('views', models.IntegerField(default=0)),
                ('ad', models.ManyToManyField(blank=True, null=True, related_name='types_of_category', to='Products.ad')),
                ('brand', models.ManyToManyField(related_name='types_of_category', to='Products.brand')),
                ('tags', models.ManyToManyField(related_name='types_of_category', to='Products.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('expiry_date', models.DateField()),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.country')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.manufacturer')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.marketer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Products.models.file_upload_to_products)),
                ('package_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productImage', to='Products.packagesize')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_highlight', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('key_ingredients', models.TextField()),
                ('key_benefits', models.TextField()),
                ('good_to_know', models.TextField(blank=True, null=True)),
                ('diet_type', models.TextField(blank=True, null=True)),
                ('help_with', models.CharField(blank=True, max_length=255, null=True)),
                ('allergen_information', models.TextField(blank=True, null=True)),
                ('product_form', models.CharField(blank=True, max_length=100, null=True)),
                ('net_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_for_use', models.TextField()),
                ('safety_information', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='Products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categorytype',
            field=models.ManyToManyField(related_name='products', to='Products.typesofcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.marketer'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='Products.tag'),
        ),
        migrations.AddField(
            model_name='packagesize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_size', to='Products.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(related_name='category', to='Products.typesofcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(related_name='categories', to='Products.tag'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.ManyToManyField(related_name='brands_tags', to='Products.tag'),
        ),
    ]
