# Generated by Django 4.2.16 on 2024-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ad',
            field=models.ManyToManyField(blank=True, related_name='brand', to='Products.ad'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='brands_tags', to='Products.tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ad',
            field=models.ManyToManyField(blank=True, related_name='categories', to='Products.ad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='category', to='Products.typesofcategory'),
        ),
        migrations.AlterField(
            model_name='typesofcategory',
            name='ad',
            field=models.ManyToManyField(blank=True, related_name='types_of_category', to='Products.ad'),
        ),
        migrations.AlterField(
            model_name='typesofcategory',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='types_of_category', to='Products.brand'),
        ),
    ]
