# Generated by Django 4.2.16 on 2024-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_tag_category_tags_product_tags_typesofcategory_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorytype',
        ),
        migrations.RemoveField(
            model_name='typesofcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='Products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorytype',
            field=models.ManyToManyField(related_name='products', to='Products.typesofcategory'),
        ),
        migrations.AddField(
            model_name='typesofcategory',
            name='category',
            field=models.ManyToManyField(related_name='types_of_category', to='Products.category'),
        ),
    ]
