# Generated by Django 4.2.16 on 2024-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.ManyToManyField(related_name='brands_tags', to='Products.tag'),
        ),
    ]
