# Generated by Django 4.2.16 on 2024-11-18 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_product_brand_alter_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='ad',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
