# Generated by Django 4.2.16 on 2024-11-18 11:21

import Products.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_ad_remove_product_ad_product_delivery_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_duration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=Products.models.file_upload_to_products),
            preserve_default=False,
        ),
    ]
