# Generated by Django 4.2.16 on 2024-11-18 12:18

import Products.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_producthighlight_productimage_package_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthighlight',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_highlight', to='Products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.file_upload_to_products),
        ),
    ]
