# Generated by Django 4.2.16 on 2024-11-20 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_product_is_on_sale_product_sale_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesize',
            name='unit_type',
            field=models.CharField(choices=[('jar', 'Jar'), ('tube', 'Tube'), ('strip', 'Strip'), ('combo_pack', 'Combo Pack'), ('pump_bottle', 'Pump Bottle'), ('packet', 'Packet'), ('sachet', 'Sachet'), ('box', 'Box'), ('bottle', 'Bottle')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
