# Generated by Django 4.2.16 on 2024-11-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_productimage_package_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
