# Generated by Django 4.2.16 on 2024-11-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthighlight',
            name='title',
        ),
    ]
