# Generated by Django 4.2.16 on 2024-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_product_average_rating_product_num_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
