# Generated by Django 4.2.16 on 2024-11-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_product_num_ratings_alter_review_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='expiry_date',
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('expiry_date', models.DateField()),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.country')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.manufacturer')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.marketer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
