# Generated by Django 4.2.16 on 2024-11-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_manufacturer_marketer_remove_brand_country_of_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
    ]
