# Generated by Django 4.2.16 on 2024-11-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_remove_product_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
