# Generated by Django 4.2.16 on 2024-11-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.marketer'),
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('key_ingredients', models.TextField()),
                ('key_benefits', models.TextField()),
                ('good_to_know', models.TextField(blank=True, null=True)),
                ('diet_type', models.TextField(blank=True, null=True)),
                ('help_with', models.CharField(blank=True, max_length=255, null=True)),
                ('allergen_information', models.TextField(blank=True, null=True)),
                ('product_form', models.CharField(blank=True, max_length=100, null=True)),
                ('net_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_for_use', models.TextField()),
                ('safety_information', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='Products.product')),
            ],
        ),
    ]
