# Generated by Django 4.2.16 on 2024-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_remove_product_description_product_marketer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand', to='Products.category'),
        ),
    ]
