# Generated by Django 4.2.16 on 2024-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brand', to='Products.category'),
        ),
    ]
