# Generated by Django 4.2.16 on 2024-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0028_alter_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ManyToManyField(related_name='ad', to='Products.category'),
        ),
    ]
