# Generated by Django 4.2.16 on 2024-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_ad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typesofcategory',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
