# Generated by Django 4.2.16 on 2024-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0030_brand_views_category_views_typesofcategory_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
