# Generated by Django 4.2.16 on 2024-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_tag_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='typeofcategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand', to='Products.typesofcategory'),
        ),
    ]
