# Generated by Django 4.2.16 on 2024-12-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_alter_brand_typeofcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='typeofcategory',
        ),
        migrations.RemoveField(
            model_name='typesofcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='Products.brand'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(related_name='category', to='Products.typesofcategory'),
        ),
        migrations.AddField(
            model_name='typesofcategory',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, related_name='types_of_category', to='Products.brand'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
