# Generated by Django 4.2.16 on 2024-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0034_remove_brand_category_remove_brand_typeofcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(related_name='category', to='Products.brand'),
        ),
        migrations.AlterField(
            model_name='typesofcategory',
            name='brand',
            field=models.ManyToManyField(related_name='types_of_category', to='Products.brand'),
        ),
    ]
