# Generated by Django 4.2.16 on 2024-12-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_rename_image_ad_img_remove_ad_category_brand_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='ad',
        ),
        migrations.AddField(
            model_name='category',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Products.ad'),
        ),
        migrations.AddField(
            model_name='typesofcategory',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types_of_category', to='Products.ad'),
        ),
    ]
