# Generated by Django 4.2.16 on 2024-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0037_remove_brand_ad_category_ad_typesofcategory_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='typesofcategory',
            name='ad',
        ),
        migrations.AddField(
            model_name='category',
            name='ad',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='Products.ad'),
        ),
        migrations.AddField(
            model_name='typesofcategory',
            name='ad',
            field=models.ManyToManyField(blank=True, null=True, related_name='types_of_category', to='Products.ad'),
        ),
    ]
