# Generated by Django 4.2.16 on 2024-12-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0038_remove_category_ad_remove_typesofcategory_ad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
