# Generated by Django 4.2.16 on 2024-12-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_remove_product_discount_percentage_and_more'),
        ('Products', '0039_delete_coupon'),
    ]

    operations = [
    ]
