# Generated by Django 4.2.16 on 2024-12-04 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0040_merge_20241205_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesize',
            name='unit_type',
            field=models.CharField(choices=[('jar', 'Jar'), ('tube', 'Tube'), ('strip', 'Strip'), ('combo_pack', 'Combo Pack'), ('pump_bottle', 'Pump Bottle'), ('packet', 'Packet'), ('sachet', 'Sachet'), ('box', 'Box'), ('bottle', 'Bottle')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='package_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productImage', to='Products.packagesize'),
        ),
    ]
